CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_HEAP_MEM_POOL_SIZE=4096

CONFIG_FPU=y
CONFIG_LOG=y
CONFIG_EVENTS=y

CONFIG_LOG_BUFFER_SIZE=8192

CONFIG_I2C=y
CONFIG_ADC=y
CONFIG_GPIO=y
CONFIG_SENSOR=y
CONFIG_SERIAL=y

CONFIG_UART_INTERRUPT_DRIVEN=y

CONFIG_GNSS=y
CONFIG_GNSS_SATELLITES=y
CONFIG_GNSS_NMEA0183=y

CONFIG_DISPLAY=y
CONFIG_SSD1306=y
CONFIG_CHARACTER_FRAMEBUFFER=y
CONFIG_CHARACTER_FRAMEBUFFER_USE_DEFAULT_FONTS=y

CONFIG_THREAD_MONITOR=y
CONFIG_THREAD_ANALYZER=y
CONFIG_THREAD_NAME=y
CONFIG_INIT_STACKS=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_SYS_HEAP_RUNTIME_STATS=y

CONFIG_BME280_TEMP_OVER_16X=y
CONFIG_BME280_PRESS_OVER_16X=y
CONFIG_BME280_HUMIDITY_OVER_16X=y
CONFIG_BME280_FILTER_16=y
