#ifndef SYSTEMSTATS_H
#define SYSTEMSTATS_H

#define PRINT_STATS 1

#define LOG_HEAP 1
#define LOG_MEMORY 1
#define LOG_DEADLINE 1
#define LOG_JITTER 1
#define LOG_LATENCY 1

#define PRINT_CALIBRATION_VALUES 0

#endif /* SYSTEMSTATS_H */